//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParameterWriter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParameterWriter.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor is avaliable only for text parameters..
        /// </summary>
        public static string ConstructorOnlyText {
            get {
                return ResourceManager.GetString("ConstructorOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements processed: .
        /// </summary>
        public static string ElementsProcessed {
            get {
                return ResourceManager.GetString("ElementsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  elems..
        /// </summary>
        public static string ForElements {
            get {
                return ResourceManager.GetString("ForElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No views found. View name should be alike: Filler#YourParamName=YourParamValue..
        /// </summary>
        public static string NoViewsFound {
            get {
                return ResourceManager.GetString("NoViewsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Mark&gt;_&lt;Comments&gt;.
        /// </summary>
        public static string ParamConstructor {
            get {
                return ResourceManager.GetString("ParamConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WL-1.
        /// </summary>
        public static string ParamConstValue {
            get {
                return ResourceManager.GetString("ParamConstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters written: .
        /// </summary>
        public static string ParametersWritten {
            get {
                return ResourceManager.GetString("ParametersWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ParamLevelName {
            get {
                return ResourceManager.GetString("ParamLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string ParamNameMark {
            get {
                return ResourceManager.GetString("ParamNameMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string ParamSourceName {
            get {
                return ResourceManager.GetString("ParamSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcs..
        /// </summary>
        public static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios processed: .
        /// </summary>
        public static string ScenariosProcessed {
            get {
                return ResourceManager.GetString("ScenariosProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsoppurted conversion.
        /// </summary>
        public static string UnsopportedConvert {
            get {
                return ResourceManager.GetString("UnsopportedConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is written for .
        /// </summary>
        public static string WriteFor {
            get {
                return ResourceManager.GetString("WriteFor", resourceCulture);
            }
        }
    }
}
